config/routes.rb
FoodpalApp::Application.routes.draw do

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  get "/errors/not_found"
  get "/errors/internal_error"
  get "/errors/unacceptable"
  get "/errors/unauthorized"

  get "omniauth_callbacks/facebook"

  get "restaurants/new"
  post "restaurants/create"

  match "products/create"

  put "products/update"

  delete "products/delete"

  post "products/edit"
  post "products/get_product"

  get "sendtext/index"
  post "sendtext/send_text_message"
  get "sms" => "receivetext#index"

  match "menus/create"

  put "menus/update"

  delete "menus/delete"
  post "menus/edit"

  match "contact", to: "static_pages#contact", as: "contact"
  match "dispatch_email", to: "static_pages#dispatch_email",
        as: "dispatch_email", method: :post


  post "comments/create"

  delete "gallery/delete"
  post "gallery/create"

  resources :gallery

  post "locations/create"

  post "restaurants/get_cuisine"

  get "restaurants/list"
  get "orders/list"

  post "products/create"

  mount Ckeditor::Engine => '/ckeditor'

  post "restaurants/craving_restaurants"
  post "restaurants/craving_blogs"



  post "cuisines/create"
  delete "cuisines/delete"

  get "orders/index"
  #get "order/:id" => "orders#show"
  resources :orders, only: [:show]
  resources :line_items

  get "locations/get_l_state"
  get "locations/get_l_city"
  get "locations/select_state"
  post "locations/edit"
  put "locations/update"
  delete "locations/delete"

  post "orders/status"
  get "orders/restaurants_orders/:id" => "orders#restaurants_orders"
  resources :carts

  get "restaurants/listing" => "restaurants#listing"

  resources :restaurants, only: [:show, :edit, :destroy, :update]
  #resources :users, only: [:edit]

  post "blogs/create"

  get "cities/index"
  resources :blogs, except: [:create]


  root :to =>  "restaurants#index"

  get "user" => "users#index"
  get "users/list"

  get "restaurants/index"
  post "restaurants/vote"


 post "restaurants/search"
post "restaurants/import_excel"
  post "restaurants/locations_import_excel"

  #get  "/restaurant/:id",   to:  "restaurants#show"

 post 'line_items/remove_item'


  get "about_us"                    => "static_pages#about_us"
  get "careers"                     => "static_pages#careers"
  get "founder_of_foodpal"          => "static_pages#founder"
  get "privacy_policy"              => "static_pages#private_policy"
  get "iphone_mobile_application"   => "static_pages#iphone"
  get "how_foodpal_works"           => "static_pages#how_works"
  get "media_kit"                   => "static_pages#media_kit"

  post "payments/payment"

  #get "blog"                        => "blogs#index"
  #get "/blogs/:id",  to:   'blogs#show'

  get "users/select_country"
  get "users/select_state"
  put "users/update"
  put "users/update"
  put "users/update_user"
  get "users/ready_city"
  get "users/get_user_state"
  get "users/get_user_city"
  put "users/update_password"
  get "users/user_edit"

  post "users/generate_new_password_email"
  #put "users/edit"

  get "receivetext/index"
  post "receivetext/voice"
  #get "receivetext/voice"

  resources :cuisines do
    get :autocomplete_cuisine_name, :on => :collection
  end

    #get "cuisines/autocomplete"

  match '/users/auth/:service/callback' => 'users/services#create'
  resources :services, :only => [:index, :create, :destroy]

  devise_for :users,  :controllers => { :sessions => "admins/sessions", :registrations=> "admins/registrations"},
                                      path_names: { edit_user_registration: "/",
                                      sign_out: "logout" }


  namespace :api do

    namespace :users do
      post "sign_in"

      post "create"
      
      post "sign_up"

      post "destroy"

      post 'orders'

      match "update"

      get "show"
    end

    namespace :orders do
      get "create_cart"
    end

    namespace :restaurants do

      post "search"

      #get "show"

      get "menu"

      get "set_select_params"

      match 'search_by_params'
      match 'search_restaurants'
      match 'get_from_current_location'


      get 'set_menu'
      get 'set_menu_items'
    end

    namespace :menus do
      match "get_menu_list"
    end

    namespace :products do
      match "get_product_list"
    end

    namespace :galleries do
      match "get_photo_list"
      match "get_first_photo"
    end

    namespace :comments do
      match "list"
    end

    namespace :payments do
      match "payment"
    end


    get 'logout' => 'devise/sessions#new'


  end

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admins do
  #     # Directs /admins/products/* to admins::ProductsController
  #     # (app/controllers/admins/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  add_breadcrumb "Home", :root_path

  def about_us
    add_breadcrumb "About Us", about_us_path
  end

  def careers
    add_breadcrumb "Careers", careers_path
  end

  def founder
    add_breadcrumb "About Us", about_us_path
    add_breadcrumb "Founder of Foodpal", founder_of_foodpal_path
  end

  def private_policy
    add_breadcrumb "About Us", about_us_path
    add_breadcrumb "Privacy Policy", privacy_policy_path
  end

  def how_works
    add_breadcrumb "How Foodpal works", how_foodpal_works_path
  end

  def media_kit
    add_breadcrumb "Media Kit", media_kit_path
  end

  def contact
    add_breadcrumb "Contact Us", contact_path
  end

  def dispatch_email





    user_info = params[:user_info]
    subject = params[:subject]

    puts user_info.inspect.red
    if ContactMailer.send_email(user_info, subject).deliver
      flash[:notice] = "Sent!"
    else
      flash[:notice] = "Could't send you message."
    end
    redirect_to contact_url
  end




end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_us.html.haml
- provide(:title, 'About Us')

.content
  %p Foodpal provides an aesthetically appealing, modern website with the ability for local restaurants to increase order volume and spotlight their brands from one network. Foodpal is dedicated to providing an advanced level of customer service to increase communication and sales, while being the "one stop shop" platform for customers and restaurant partners. 

  %p We have initialized our newest Foodpal Points Program, a customer-restaurant loyalty rewards program to attract new customers and encourage existing customers to return with a smile. Foodpal is up-to-date and prepared to reach more customers with our intuitive application for Iphone, Ipad and Android mobile devices, while constantly developing new communication tools to evolve our network.

  %p Foodpal Plan
  %p Foodpal`s plan is simple and easy. Restaurant partners have the power to create their own program that works for their business. Restaurant partners can promote their specials and change promotions at their leisure. There are no annual fees or monthly subscription contract for our network. Restaurant partners increase sales with a hassle-free program ordering service. 
  %ul
    %li No monthly subscriptions
    %li No annual fee
    %li Restaurant partners establish a minimum order amount
    %li Restaurant partners can encourage customer`s to order more
    %li Cancel anytime policy
   
  %p Sign-up now for our Introductory Promotion: NO Order FEES Until July 2013!
  %p
    Still not convinced? Try us out without Our Foodpal order fees until July 2013. Customers can order as little or as much as they want without the worry of our pyramid prices. See terms and agreements for more details or contact us at 
    %a{href: "mailto:info@foodpal.com", target: "_blank"}> info@foodpal.com
    \. Processing fees not included. 

app/views/static_pages/careers.html.haml
- provide(:title, 'Careers')
.content
  %div{style: "float:left;width: 530px;"}
    %h4 Careers
    %div Are you interested in applying your skills with a fast-paced and driven company? Are you looking for a positive atmosphere and work-life balance mentality when it comes to the step in your career?
    %div  
    %div
      Foodpal provides its employees with a creative and productive environment, while the brand expands its markets around the country. Currently, Foodpal is looking for driven and talented individuals to join the team. With the unique opportunities available in our creative, marketing, accounting and IT departments, recent graduates and experienced candidates are welcome to apply. If you are passionate about computer development field or think you fit the bill to put your sales and marketing skills to good use with one of the fastest growing companies in the nation, send your cover letter and resume to 
      %a{href: "mailto:careers@foodpal.com", target: "_blank"}> careers@foodpal.com
      \ and we will contact you within 24 hours. 
    %div  
    %div
      %h4 Available Opportunities:
    %ul
      %li Director of Accounting
      %li Marketing Coordinator
      %li Graphic Designer I
  %div{style: "float:left;"}
    %img{alt: "", src: "/assets/career picture.jpg", style: "width: 367px; height: 408px;padding: 0;border: 0; margin: 0"}/
  #lineSeparator
  %div{style: "float:left;width: 530px;"}
    %h4 Interships 2013
    %p
      Still in school and looking for course credit and an opportunity to earn cash? An internship is a great way to get your foot in the door and one step closer to the workforce! As a rapidly expanding company and our staff is looking to find the newest and brightest candidates before graduation! Foodpal is now recruiting individuals for internship positions in our marketing and IT departments. Our 2013 is scheduled to begin, see below about how you can join our team and strengthen your resume at the same time!
      %p
        If you are currently over the age of 18 and in college or entering a two to four year college or university, apply here or send your resume to
        %a{href: "mailto:internships@foodpal.com"} internships@foodpal.com
        and we will contact you within 24 hours.
    %h4.p1 Upcoming 2014 Internship Programs 
    %p.p2  
    %p.p1 Still in school and looking for course credit and an opportunity to earn experience with bonus incentives? An internship is a great way to get your foot in the door and one step closer to the workforce! As a rapidly expanding company, our staff is looking to find the newest and brightest candidates to add to our team.  We are currently interviewing candidates for the 2013 semester and upcoming 2014 semester.  Che Find out how you can join our team and strengthen your resume at the same time!
    %p.p2  
    %p.p1
      If you are entering a two to four year college or university, email your resume to
      %a{href: "mailto:internships@foodpal.com"} info@foodpal.com
      and we will contact you as soon as possible! 
  #careerPerks.green-block{style: "float:left;width: 367px;"}
    %h4{style: "text-align: center;"} PERKS
    %ul
      %li.li1 Course Credit Opportunities
      %li.li1 Flexible Hours
      %li.li1 4, 8, 10 or 12 week Internship Programs
      %li.li1 Rewarding Bonus Programs
      %li.li1 Receive recommendation letters and LinkedIn recommendations with requests
      %li.li1 Opportunities to earn experience and learn more about areas in IT Development, Graphic Design and Marketing
  %p{style: "text-align:center;margin-top:10px;"}
    %img{alt: "", src: "/assets/bottom map.jpg", style: "padding: 0;border: 0;"}/

app/views/static_pages/contact.html.haml
.content
  .contact-form

    = form_tag dispatch_email_path, method: :post , id: "contact_form" do
      = label_tag "user_info[name]", "Name"
      = text_field_tag "user_info[name]","", class: "white required"
      = label_tag "user_info[email]", "Email"
      = text_field_tag "user_info[email]","", class: "white required email"
      = label_tag "subject", "Subject"
      = text_field_tag "subject","", class: "white"
      = label_tag "user_info[message]", "Message"
      = text_area_tag "user_info[message]", "", class: "white required"
      = show_simple_captcha
      = submit_tag "Send Message", class: "dark", style: "padding: 5px 15px;"

app/views/static_pages/founder.html.haml
.content

  %img{alt: "", src: "/assets/379226_10151529228697425_553253535_n.jpg", style: "width: 200px; height: 267px; float: left;"}
  %div
    %p In 2010, Foodpal was a concept created by founder, Stefan Moczarski. Moczarski was accustomed to traveling the world during their high school and college careers; visiting the local hotspots and exploring the different cultures one-by-one. During his globetrotting journeys, Moczarski wined and dined in some of the most exotic cities in the world.  
    %p The restaurants in South America and the cafes in Europe were just as popular as the dining establishments in the United States. Although, without a means of marketing these “hidden gem” restaurants, new customers would never know they existed. Establishments inside and outside the United States were missing out on new business sales, and introducing new customers to their delicious menu items.  

    %p Moczarski decided to take matters into his own hands and develop an online platform to spread the word about these businesses.  It only made sense to begin this endeavor in the area they knew best; His home city of Miami, Florida. The city was an ideal business launch location, and his hopes to expand internationally would not be far behind.

app/views/static_pages/how_works.html.haml
.content
  %img(src="/assets/works.jpg" )

app/views/static_pages/iphone.html.haml
.content
  %p
    %img{alt: "", src: "/assets/icon.jpg", style: "font-size: 13px; line-height: 20px; background-color: rgb(255, 255, 255); width: 111px; height: 200px; float: left; border-width: 0px; border-style: solid; margin: 10px;"}/
  %p
    %span{style: "font-size: 13px;"} Let your iPhone become your lunch-saver! Search – Choose – Order – and Enjoy your favorite dish with FoodPal. Our applications lets you to order online anywhere anytime. Can you imagine something more comfortable?
  %div
    %div{style: "font-size: 13px; line-height: 20px;"}  
    %div{style: "font-size: 13px; line-height: 20px;"} The functions of FoodPal are set on a way that makes your everyday order more interesting. Thanks to search-box you can discover a lot of interesting, may be unknown restaurants for you. You can try various cuisines beginning from Asian food to classical American one.
    %p{style: "font-size: 13px;margin-left: 80px; font-size: 13px;"}  
    %p{style: "font-size: 13px;margin-left: 80px; font-size: 13px;"}  
    %p{style: "font-size: 13px;margin-left: 80px; font-size: 13px;"}  
    %p{style: "font-size: 13px;margin-left: 80px; font-size: 13px;"}  
    %p{style: "font-size: 13px;margin-left: 80px; font-size: 13px;"}  
    %ul{style: "font-size: 13px; line-height: 20px;"}
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} Download FoodPal’s application to your iPhone.
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} Register yourself taking a few general steps: enter your name, postal address, e-mail address and you are ready!
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} The search-box makes easier to filter restaurants by city and cuisine.
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} View the menus, read the ratings and comments for each restaurant. Rating and comments help you a lot in choosing. They usually tell all the pros and contras of a given place, food.
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} Discover new places and exotic foods by one click!
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} Choose between delivery and pick-up. A perfect solution to order and grab with yourself. Fast and easy!
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} See what FoodPal recommends for you with the FoodPal recommendation system.
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} History allows you to see what you’ve ordered and make a reorder if desired. Also it shows the operations you made on FoodPal, if you paid for the items or you just added to cart, have you already place the order, has it already delivered etc. It offers you a great comfort. 
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} If you are not sure how to use the application – there is an option with general help. Don’t hesitate to use it!
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} All the main options are put in this application: cart, search system, general options and settings.
      %li{style: "font-size: 13px;"}
        %p{style: "margin-left: 40px; font-size: 13px;"} FoodPal offers you hundreds of restaurants and a wide range of cuisine in one click anywhere, anytime.
    %div{style: "font-size: 13px; line-height: 20px;"}  
    %div{style: "font-size: 13px; line-height: 20px;"} The easiest way to order online - FoodPal.
    %div{style: "font-size: 13px; line-height: 20px;"}
      %span{style: "font-size: 13px; line-height: 20px;"}
         * Please
        %a{href: "http://foodpal.com/contact"} contact us
        if you have questions.
    %div{style: "font-size: 13px; line-height: 20px;"} Screenshots:
    %div{style: "font-size: 13px; line-height: 20px;"}
      %table{border: "1", cellpadding: "1", cellspacing: "1", style: "font-size: 13px; width: 500px;", class: "panel default-panel"}
        %tbody{style: "font-size: 13px;"}
          %tr{style: "font-size: 13px;"}
            %td{style: "font-size: 13px;"}  
            %td{style: "font-size: 13px;"}
              %img{alt: "", src: "/assets//p3.jpg", style: "font-size: 13px; background-color: rgb(255, 255, 255); line-height: 20px; width: 204px; height: 300px;"}/
            %td{style: "font-size: 13px;"}
              %img{alt: "", src: "/assets//p4.jpg", style: "font-size: 13px; background-color: rgb(255, 255, 255); line-height: 20px; width: 204px; height: 300px;"}/
          %tr{style: "font-size: 13px;"}
            %td{style: "font-size: 13px;"}
              %img{alt: "", src: "/assets//p6.jpg", style: "font-size: 13px; background-color: rgb(255, 255, 255); line-height: 20px; width: 204px; height: 300px;"}/
            %td{style: "font-size: 13px;"}
              %img{alt: "", src: "/assets//p16.jpg", style: "font-size: 13px; background-color: rgb(255, 255, 255); line-height: 20px; width: 204px; height: 300px;"}/
            %td{style: "font-size: 13px;"}
              %img{alt: "", src: "/assets//p14.jpg", style: "width: 204px; height: 300px;"}/
      %p{style: "font-size: 13px; text-align: center;"}  
      %p{style: "font-size: 13px;"}  
    %p{style: "font-size: 13px; line-height: 20px;"}  
  %p  
  %p  

app/views/static_pages/media_kit.html.haml
.content.medias
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    / Indicators
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "3", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "4", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "5", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "6", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "7", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "8", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "9", "data-target" => "#carousel-example-generic"}
    / Wrapper for slides
    .carousel-inner
      .item.active
        %img{src: "/assets/media_kit/1.png"}
      .item
        %img{src: "/assets/media_kit/2.png"}
      .item
        %img{src: "/assets/media_kit/3.png"}
      .item
        %img{src: "/assets/media_kit/4.png"}
      .item
        %img{src: "/assets/media_kit/5.png"}
      .item
        %img{src: "/assets/media_kit/6.png"}
      .item
        %img{src: "/assets/media_kit/7.png"}
      .item
        %img{src: "/assets/media_kit/8.png"}
      .item
        %img{src: "/assets/media_kit/9.png"}

    / Controls
    %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-example-generic"}
      %span.glyphicon.glyphicon-chevron-left
    %a.right.carousel-control{"data-slide" => "next", href: "#carousel-example-generic"}
      %span.glyphicon.glyphicon-chevron-right