config/routes.rb
FoodpalApp::Application.routes.draw do

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  get "/errors/not_found"
  get "/errors/internal_error"
  get "/errors/unacceptable"
  get "/errors/unauthorized"

  get "omniauth_callbacks/facebook"

  get "restaurants/new"
  post "restaurants/create"

  match "products/create"

  put "products/update"

  delete "products/delete"

  post "products/edit"
  post "products/get_product"

  get "sendtext/index"
  post "sendtext/send_text_message"
  get "sms" => "receivetext#index"

  match "menus/create"

  put "menus/update"

  delete "menus/delete"
  post "menus/edit"

  match "contact", to: "static_pages#contact", as: "contact"
  match "dispatch_email", to: "static_pages#dispatch_email",
        as: "dispatch_email", method: :post


  post "comments/create"

  delete "gallery/delete"
  post "gallery/create"

  resources :gallery

  post "locations/create"

  post "restaurants/get_cuisine"

  get "restaurants/list"
  get "orders/list"

  post "products/create"

  mount Ckeditor::Engine => '/ckeditor'

  post "restaurants/craving_restaurants"
  post "restaurants/craving_blogs"



  post "cuisines/create"
  delete "cuisines/delete"

  get "orders/index"
  #get "order/:id" => "orders#show"
  resources :orders, only: [:show]
  resources :line_items

  get "locations/get_l_state"
  get "locations/get_l_city"
  get "locations/select_state"
  post "locations/edit"
  put "locations/update"
  delete "locations/delete"

  post "orders/status"
  get "orders/restaurants_orders/:id" => "orders#restaurants_orders"
  resources :carts

  get "restaurants/listing" => "restaurants#listing"

  resources :restaurants, only: [:show, :edit, :destroy, :update]
  #resources :users, only: [:edit]

  post "blogs/create"

  get "cities/index"
  resources :blogs, except: [:create]


  root :to =>  "restaurants#index"

  get "user" => "users#index"
  get "users/list"

  get "restaurants/index"
  post "restaurants/vote"


 post "restaurants/search"
post "restaurants/import_excel"
  post "restaurants/locations_import_excel"

  #get  "/restaurant/:id",   to:  "restaurants#show"

 post 'line_items/remove_item'


  get "about_us"                    => "static_pages#about_us"
  get "careers"                     => "static_pages#careers"
  get "founder_of_foodpal"          => "static_pages#founder"
  get "privacy_policy"              => "static_pages#private_policy"
  get "iphone_mobile_application"   => "static_pages#iphone"
  get "how_foodpal_works"           => "static_pages#how_works"
  get "media_kit"                   => "static_pages#media_kit"

  post "payments/payment"

  #get "blog"                        => "blogs#index"
  #get "/blogs/:id",  to:   'blogs#show'

  get "users/select_country"
  get "users/select_state"
  put "users/update"
  put "users/update"
  put "users/update_user"
  get "users/ready_city"
  get "users/get_user_state"
  get "users/get_user_city"
  put "users/update_password"
  get "users/user_edit"

  post "users/generate_new_password_email"
  #put "users/edit"

  get "receivetext/index"
  post "receivetext/voice"
  #get "receivetext/voice"

  resources :cuisines do
    get :autocomplete_cuisine_name, :on => :collection
  end

    #get "cuisines/autocomplete"

  match '/users/auth/:service/callback' => 'users/services#create'
  resources :services, :only => [:index, :create, :destroy]

  devise_for :users,  :controllers => { :sessions => "admins/sessions", :registrations=> "admins/registrations"},
                                      path_names: { edit_user_registration: "/",
                                      sign_out: "logout" }


  namespace :api do

    namespace :users do
      post "sign_in"

      post "create"
      
      post "sign_up"

      post "destroy"

      post 'orders'

      match "update"

      get "show"
    end

    namespace :orders do
      get "create_cart"
    end

    namespace :restaurants do

      post "search"

      #get "show"

      get "menu"

      get "set_select_params"

      match 'search_by_params'
      match 'search_restaurants'
      match 'get_from_current_location'


      get 'set_menu'
      get 'set_menu_items'
    end

    namespace :menus do
      match "get_menu_list"
    end

    namespace :products do
      match "get_product_list"
    end

    namespace :galleries do
      match "get_photo_list"
      match "get_first_photo"
    end

    namespace :comments do
      match "list"
    end

    namespace :payments do
      match "payment"
    end


    get 'logout' => 'devise/sessions#new'


  end

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admins do
  #     # Directs /admins/products/* to admins::ProductsController
  #     # (app/controllers/admins/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'


end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :avatar

  has_one :address, :dependent => :destroy
  has_many :orders
  has_many :sessions
  has_many :blogs, :dependent => :destroy
  has_many :restaurants
  has_and_belongs_to_many :roles
  has_many :services, :dependent => :destroy
  has_many :ratings


  apply_simple_captcha :message => "The secret Image and code were different", :add_to_base => true
  has_one :address
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :name, :login, :password_confirmation, :remember_me, :captcha,:captcha_key, :phone, :avatar, :role_ids, :address_id
  # attr_accessible :title, :body
  attr_accessor :validation_confirm
  #cattr_accessor :skip_callbacks
  before_create :check_captcha
  validates_presence_of :login
  validates :login, uniqueness: true
  #validate :check_capture
  #skip_callback :before_save



  has_attached_file :avatar,
                    :url  => "/uploads/images/users/:id/:style/:filename.:extension",
                    :default_url => "/assets/imagenotavailable.png",
                    :path => ":rails_root/public/uploads/images/users/:id/:style/:filename.:extension",
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }



  def check_captcha

    self.valid_with_captcha? unless  validation_confirm == 'api'
  end

  def role?(role)
    self.roles.find_by_name(role.to_s.camelize)
  end






end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

    before_filter :authenticate_user!, only: [:index]
    before_filter :api_authentikate_user, except: [:create, :sign_in, :sign_up, :index, :destroy]
    respond_to :json

    def create
      puts params
      Rails.logger.info "Year: #{params}"

      user = User.new(params[:user])

      puts '-----------------------validation-----------------------------------' if user.valid?
      puts user.valid?                                                            if user.valid?


      if user.valid?
        puts "------save user----------------"
        #user.skip_validation_inst = true

        user.validation_confirm = 'api'
        #User.skip_callback
        puts user.save

        session = create_session(user)
        puts Session.create(session)
	

        render :json=> {:auth_token=>session[:auth_token], :email=>user.email, user: user.as_json} , :status=>201

      else

        render :json=> user.errors, :status=>422
      end
    end
    
    def sign_up
      puts params
      Rails.logger.info "Year: #{params}"

      user = User.new(params[:user])

      puts '-----------------------validation-----------------------------------' if user.valid?
      puts user.valid?                                                            if user.valid?


      if user.valid?
        puts "------save user----------------"
        #user.skip_validation_inst = true

        user.validation_confirm = 'api'
        #User.skip_callback
        puts user.save

        session = create_session(user)
        puts Session.create(session)
	

        render :json=> {:auth_token=>session[:auth_token], :avatar=>user.avatar.url(:thumb), :email=>user.email, user: user.as_json} , :status=>201

      else

        render :json=> {:errors=>user.errors}, :status=>422
      end
    end

    def sign_in
      puts "sign in ---------------------------------------------------------".red.bold

      user = User.find_for_database_authentication(:login=> params[:user][:login])

      puts "-user---#{user}-----------------------".green
      if user && user.valid_password?(params[:user][:password])


        session = create_session(user)
        Session.create(session)

        puts user.inspect.red
        render :json=> {:auth_token=>session[:auth_token], :avatar=>user.avatar.url(:thumb) ,:email=>user.email, user: user.as_json} , :status=>201

      else
        bad_request ['Invalid login or password'], 401
      end

    end



    def index

    end


    def destroy

      session = Session.where(:auth_token => params[:authentication_token]).first
      if session
        #render json: session
        destroy_session(session)    if session
        render :json => { :success => true,  :info => "Logged out", :status => 200 }
      else
        bad_request ['invalid login or password'], 433
      end
    end



    def show
      render json: {user: @current_user.as_json}

    end


    def update
      puts '------update-----------------------'
      puts params
      user = User.new
      user.assign_attributes(params[:user])

      puts user.valid?

      if  @current_user.update_attributes(params[:user])
        render json: {user: @current_user.as_json}
      else
        render :json=> @current_user.errors, :status=>422
      end

    end


    def orders
      puts params.inspect.red
      @orders = @current_user.orders
      orders = [];


      puts params.inspect.red
      @orders = @current_user.orders
      orders = []
      @orders.each do |order|
        puts "----status---------------------#{order.status.inspect}"
        number = order.transaction_id ? order.transaction_id : 'cash'
        status =  (order.status)?  order.status.title : 'Not paid'
        orders << {number: number, state: status }
      end

      render json: orders.to_json

    end


    private


    def create_session(user)

      range = [*'0'..'9', *'a'..'z', *'A'..'Z']
      session = {user_id: user.id, auth_token: Array.new(30){range.sample}.join, updated_at: Time.now}
      session

    end

    def destroy_session session

      session.destroy
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :unauthorized, except: [:generate_new_password_email]
  before_filter :authenticate_user!, except: [:generate_new_password_email, :edit_user_password]


  add_breadcrumb "Home", :root_path

  def index
  puts current_user.inspect.yellow
  puts params.inspect.green
    if params[:user_id]
      user =  User.find_by_id(params[:user_id])
      sign_in user
    end

    @user = User.find(current_user.id)
    @user.address = Address.new unless @user.address

    @country = Country.new

    @state = State.new

    add_breadcrumb current_user.name, :user_path
  end


  def update
    puts params.inspect.yellow.bold


    @user = User.find_by_id(current_user.id)

    if @user.update_attributes(params["user"])

      @user.address ? @user.address : @user.address = Address.create

      @user.address.update_attributes(params[:address])

    end
    puts @user.errors.messages.inspect.red.bold
    redirect_to user_path
  end

  def update_user
    puts params.inspect.yellow.bold


    @user = User.find_by_id(params["user"]["id"])

    if @user.update_attributes(params["user"])

      @user.address ? @user.address : @user.address = Address.create

      @user.address.update_attributes(params[:address])

    end
    puts @user.errors.messages.inspect.red.bold
    redirect_to users_list_path
  end

  def select_country
    country = Country.find_by_id(params[:id])
    @states = country.states

    render json: @states
  end

  def select_state
    state = State.find_by_id(params[:id])
    @cities = state.cities.order(:city)

    render json: @cities
  end

  def ready_city
    state = current_user.address.city.state
    @cities = state.cities.order(:city)

    render json: @cities
  end

  def get_user_state
    puts "State".green
    puts current_user.address.inspect.light_blue

    state = current_user.address.city.state if current_user.address.city


    puts state.inspect.magenta.bold

    render json: state
  end

  def get_user_city
    city = current_user.address.city

    render json: city
  end

  def update_password

    puts params.inspect.green

    @user = current_user

    if @user.update_attributes(params[:user])

      puts current_user.inspect.blue
      redirect_to user_path({user_id: @user.id}), :notice => "Succes update"
    else
      sign_in @user
      redirect_to user_path({user_id: @user.id}), :notice => @user.errors.messages
    end

  end

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.required(:user).permit(:password, :password_confirmation)
  end

  def list
    #@users = User.paginate(:page => params[:page], :per_page => 20)
    @tasks_grid = initialize_grid(User, :include => [:roles])

    add_breadcrumb current_user.name, :user_path
    add_breadcrumb "Users Management", :users_list_path
  end

  def user_edit
    @user = User.find_by_id(params[:id])
    @user.address = Address.new unless @user.address
    @roles = Role.all

    add_breadcrumb current_user.name, :user_path
    add_breadcrumb "Users Management", :users_list_path
    add_breadcrumb "Edit \"" + @user.name + "\"" , :users_list_path
    render "users/edit"
  end

  def generate_new_password_email
    puts params.inspect.red
    user = User.where(email: params[:user][:email]).first

    if user
      user.send_reset_password_instructions
      flash[:notice] = "Reset password instructions have been sent to #{user.email}."
      redirect_to root_path
    else
      flash[:notice] = "Foodpal does not have this email listed in the database. Please create a new account or contact us at info@foodpal.com for more information."
      redirect_to :back
    end
  end

end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_grid.html.haml
-#- show_filters: :when_filtered
=  grid(@tasks_grid, show_filters: :when_filtered, allow_showing_all_records:  false) do |g|
  - g.column name:  '#', attribute: 'id'
  - g.column name:  'Name', attribute: 'name' do |task|
    - link_to(task.name,users_user_edit_path({id: task}))
  - g.column :name => "Email", attribute: 'email'

  - g.column :name => "Role", attribute: "name", model: "Role", custom_filter: %w(Admin Customer User) do |task|
    -#- custom_filter: Role.to_dropdown do |task|
    - task.roles.collect{|role| role.name}.to_sentence

  - g.column name:  '' do |task|
    - raw "<div>
    - <span class=\"label label-primary\">Restaurants: #{task.restaurants.count}</span>
    - <span class=\"label label-success\">Blogs: #{task.blogs.count}</span>
    - <span class=\"label label-default\">Orders: #{task.orders.count}</span>
    - </div>"

  - g.blank_slate content_tag(:div, "No restourants found", class: 'well')

app/views/users/edit.html.haml
.content
  .post#edit
    - if @user
      = form_for @user, url: "/users/update_user",  :html => { :multipart => true }  do |form|
        .row{style: "margin: 0"}
          .col-xs-5
            %h1
              Edit
              = @user.name
          .col-xs-2
            = form.submit "Save Changes", class: "btn btn-success"
            = hidden_field_tag "user[id]", @user.id

        %table
          %tr
            %td
              = image_tag @user.avatar.url(:thumb)
              = form.file_field  :avatar
            %td
              - if @user.id != current_user.id
                = form.label :role
                = form.select "role_ids", options_from_collection_for_select(@roles, "id", "name", (@user.roles.first.id if @user.roles.first)), include_blank: true, :class => "simple"
          %tr
            %td
              = form.label :name
              = form.text_field :name, :class => "white"
            %td
              = form.label :login
              = form.text_field :login, :class => "white"
          %tr
            %td
              = form.label :email
              = form.text_field :email, :class => "white"
            %td
              = form.label :phone
              = form.text_field :phone, :class => "white"
          %tr
            %td

              -##country
              -#  = collection_select(:country, :id, Country.all, :id, :short_name)
              = label_tag "State"
              #state.styled-select
                = collection_select(:state, :id, State.all, :id, :state)
            %td
              = label_tag "City"
              #city.styled-select{style: "display: none"}
                = collection_select(:address, :city_id, [], :id, :city)

            %tr
              %td
                = fields_for @user.address do |a|
                  = a.label :address
                  = a.text_field :address, :class => "white"

          %tr
            %td

app/views/users/index.html.haml
- provide(:title, current_user.name)

-##flash-message
-#  - flash.each do |name, msg|
-#    = content_tag :div, msg, :id => "flash_#{name}"

- Time::DATE_FORMATS[:datetime] = "%m/%d/%Y at %k:%M"
.content

  %ul.nav.nav-tabs
    %li{class: "active"}
      %a{"data-toggle" => "tab", href: "#view"} View
    %li
      %a{"data-toggle" => "tab", href: "#edit"} Edit
    %li
      %a{"data-toggle" => "tab", href: "#pass"} Change Password

    %li.dropdown
      %a#setting.dropdown-toggle{"data-toggle" => "dropdown", href: "#", role: "button"}
        Management
        %b.caret
      %ul.dropdown-menu{"aria-labelledby" => "setting", role: "menu"}
        %li
          = link_to "Orders List", orders_list_path
        - if can? :manage, Restaurant
          %li
            = link_to "Restaurants Management", restaurants_list_path

        - if can? :update, @users
          %li
            = link_to "User Management", users_list_path


  .tab-content
    #view.tab-pane.active
      .post
        %h1 User info
        .row{style: "margin: 0"}

          .col-xs-3
            = image_tag current_user.avatar.url(:thumb)

          .col-xs-9
            %table
              %tr
                %th
                  Full Name
                %td
                  = current_user.name
              %tr
                %th
                  Login
                %td
                  = current_user.login
              %tr
                %th
                  Email
                %td
                  = current_user.email
              %tr
                %th
                  Phone
                %td
                  = current_user.phone

              %tr
                %th
                  Address
                %td
                  = current_user.address.city.state.country.short_name + ", " +  current_user.address.city.state.state + ", " + current_user.address.city.city + ", " + current_user.address.address if current_user.address.city if current_user.address
              %tr
                %th
                  Last Login At
                %td
                  = current_user.last_sign_in_at.to_s(:datetime)

    #edit.tab-pane
      .post
        = form_for @user, url: "users/update",  :html => { :multipart => true }  do |form|
          .row{style: "margin: 0"}
            .col-xs-5
              %h1 Edit User
            .col-xs-2
              = form.submit "Save Changes", class: "btn btn-success"

          %table
            %tr
              %td
                = image_tag current_user.avatar.url(:thumb)
                = form.file_field  :avatar
            %tr
              %td
                = form.label :name
                = form.text_field :name, :class => "white"
              %td
                = form.label :login
                = form.text_field :login, :class => "white"
            %tr
              %td
                = form.label :email
                = form.text_field :email, :class => "white"
              %td
                = form.label :phone
                = form.text_field :phone, :class => "white"
            %tr
              %td

                -##country
                -#  = collection_select(:country, :id, Country.all, :id, :short_name)
                = label_tag "State"
                #state.styled-select
                  = collection_select(:state, :id, State.all, :id, :state)
              %td
                = label_tag "City"
                #city.styled-select{style: "display: none"}
                  = collection_select(:address, :city_id, [], :id, :city)

              %tr
                %td
                  = fields_for @user.address do |a|
                    = a.label :address
                    = a.text_field :address, :class => "white"


            %tr
              %td




    #pass.tab-pane
      .post

        %h1
          Edit
        = form_for(current_user, :url => users_update_password_path(current_user), :html => { :method => :put }) do |f|

          .field
            = f.label :password
            = f.password_field :password, :autocomplete => "off", :class => "white"
          .field
            = f.label :password_confirmation
            = f.password_field :password_confirmation, :class => "white"

          .field{style: "margin: 10px"}
            = f.submit "Update", :class => "btn btn-danger"

app/views/users/list.html.haml
.content
  .post
    = render partial:  'grid'


    -#- if @users

  -#    %table.table.tablesorter
  -#      %thead
  -#        %tr
  -#          %th #
  -#          %th Name
  -#          %th Role
  -#          %th
  -#
  -#
  -#      - @users.each do |u|
  -#        %tr
  -#          %td
  -#            = u.id
  -#          %td
  -#            = link_to u.name, edit_user_path(u), class: "restaurant_#{u.id}", "data-value" => u.id if u.id != current_user.id
  -#            = u.name if u.id == current_user.id
  -#
  -#          %td
  -#            = u.roles.first.name if u.roles.first
  -#
  -#          %td
  -#            %span.label.label-primary
  -#              Restaurants:
  -#              = u.restaurants.count
  -#            %span.label.label-success
  -#              Blogs:
  -#              = u.blogs.count
  -#
  -#            %span.label.label-default
  -#              Orders:
  -#              = u.orders.count
  -#
  -#    = will_paginate @users, renderer: BootstrapPagination::Rails
  -#
  -#  - else
  -#    %h1 No Any Restaurants
  -#
  -#:javascript
  -#  $(function(){
  -#    $("table.table.tablesorter").tablesorter({
  -#      sortList:[
  -#        [0,0]
  -#      ],
  -#      headers: {
  -#        0: {
  -#            sorter: "digit"
  -#        },
  -#        1: {
  -#            sorter: "text"
  -#        },
  -#        2: {
  -#            sorter: "text"
  -#        },
  -#        3: {
  -#            sorter: "false"
  -#        }
  -#      },
  -#    });
  -#  });