config/routes.rb
FoodpalApp::Application.routes.draw do

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  get "/errors/not_found"
  get "/errors/internal_error"
  get "/errors/unacceptable"
  get "/errors/unauthorized"

  get "omniauth_callbacks/facebook"

  get "restaurants/new"
  post "restaurants/create"

  match "products/create"

  put "products/update"

  delete "products/delete"

  post "products/edit"
  post "products/get_product"

  get "sendtext/index"
  post "sendtext/send_text_message"
  get "sms" => "receivetext#index"

  match "menus/create"

  put "menus/update"

  delete "menus/delete"
  post "menus/edit"

  match "contact", to: "static_pages#contact", as: "contact"
  match "dispatch_email", to: "static_pages#dispatch_email",
        as: "dispatch_email", method: :post


  post "comments/create"

  delete "gallery/delete"
  post "gallery/create"

  resources :gallery

  post "locations/create"

  post "restaurants/get_cuisine"

  get "restaurants/list"
  get "orders/list"

  post "products/create"

  mount Ckeditor::Engine => '/ckeditor'

  post "restaurants/craving_restaurants"
  post "restaurants/craving_blogs"



  post "cuisines/create"
  delete "cuisines/delete"

  get "orders/index"
  #get "order/:id" => "orders#show"
  resources :orders, only: [:show]
  resources :line_items

  get "locations/get_l_state"
  get "locations/get_l_city"
  get "locations/select_state"
  post "locations/edit"
  put "locations/update"
  delete "locations/delete"

  post "orders/status"
  get "orders/restaurants_orders/:id" => "orders#restaurants_orders"
  resources :carts

  get "restaurants/listing" => "restaurants#listing"

  resources :restaurants, only: [:show, :edit, :destroy, :update]
  #resources :users, only: [:edit]

  post "blogs/create"

  get "cities/index"
  resources :blogs, except: [:create]


  root :to =>  "restaurants#index"

  get "user" => "users#index"
  get "users/list"

  get "restaurants/index"
  post "restaurants/vote"


 post "restaurants/search"
post "restaurants/import_excel"
  post "restaurants/locations_import_excel"

  #get  "/restaurant/:id",   to:  "restaurants#show"

 post 'line_items/remove_item'


  get "about_us"                    => "static_pages#about_us"
  get "careers"                     => "static_pages#careers"
  get "founder_of_foodpal"          => "static_pages#founder"
  get "privacy_policy"              => "static_pages#private_policy"
  get "iphone_mobile_application"   => "static_pages#iphone"
  get "how_foodpal_works"           => "static_pages#how_works"
  get "media_kit"                   => "static_pages#media_kit"

  post "payments/payment"

  #get "blog"                        => "blogs#index"
  #get "/blogs/:id",  to:   'blogs#show'

  get "users/select_country"
  get "users/select_state"
  put "users/update"
  put "users/update"
  put "users/update_user"
  get "users/ready_city"
  get "users/get_user_state"
  get "users/get_user_city"
  put "users/update_password"
  get "users/user_edit"

  post "users/generate_new_password_email"
  #put "users/edit"

  get "receivetext/index"
  post "receivetext/voice"
  #get "receivetext/voice"

  resources :cuisines do
    get :autocomplete_cuisine_name, :on => :collection
  end

    #get "cuisines/autocomplete"

  match '/users/auth/:service/callback' => 'users/services#create'
  resources :services, :only => [:index, :create, :destroy]

  devise_for :users,  :controllers => { :sessions => "admins/sessions", :registrations=> "admins/registrations"},
                                      path_names: { edit_user_registration: "/",
                                      sign_out: "logout" }


  namespace :api do

    namespace :users do
      post "sign_in"

      post "create"
      
      post "sign_up"

      post "destroy"

      post 'orders'

      match "update"

      get "show"
    end

    namespace :orders do
      get "create_cart"
    end

    namespace :restaurants do

      post "search"

      #get "show"

      get "menu"

      get "set_select_params"

      match 'search_by_params'
      match 'search_restaurants'
      match 'get_from_current_location'


      get 'set_menu'
      get 'set_menu_items'
    end

    namespace :menus do
      match "get_menu_list"
    end

    namespace :products do
      match "get_product_list"
    end

    namespace :galleries do
      match "get_photo_list"
      match "get_first_photo"
    end

    namespace :comments do
      match "list"
    end

    namespace :payments do
      match "payment"
    end


    get 'logout' => 'devise/sessions#new'


  end

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admins do
  #     # Directs /admins/products/* to admins::ProductsController
  #     # (app/controllers/admins/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'


end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  # attr_accessible :title, :body
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def api_add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity +=1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item.save
    current_item
  end

  def remove_product(line_item)
    puts '----------------------------remove-----product------------------------'
    puts line_item.inspect.green.bold
    if line_item.quantity > 1
      line_item.quantity -=1
      line_item.save

    else
      line_item.destroy
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_edit.html.haml
.modal-content
  .loading.product
    %img(src="/assets/loading.gif" ){style: "margin: 0 auto"}
  = form_tag "/line_items", method: "POST", id: "add_cart_form" do
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
      %h4.modal-title
        Add "#{product.name}" to cart
    .modal-body
      .article
        = image_tag product.image.url(:thumb), style: "float: left; margin: 0 10px 10px 0; width: 150px"
        %p
          = product.description

      .row{style: "clear: both"}

        .col-xs-4
          = label_tag "Quantity:"
          - val = 1
          - val = product.line_items.where(cart_id: cart.id).first.quantity if product.line_items.where(cart_id: cart.id).first
          %input{max: "30", min: "1", name: "line_item[quantity]", type: "number", value: val}
        .col-xs-5
          Base Price:
          .price
            $
            = product.price
        .col-xs-3

    .modal-footer
      .row
        .col-xs-4{style: "text-aligh: left"}
          = submit_tag "Remove from Cart",  class: "btn btn-danger remove_from_cart_btn", name: "remove", :confirm => "Are you shure?" if product.line_items.where(cart_id: cart.id).first
        .col-xs-3.col-md-4

        .col-xs-4{style: "text-aligh: right"}
          = hidden_field_tag "line_item[product_id]", product.id
          = submit_tag "Add To Cart",  class: "btn btn-info add_to_cart_btn", name: "add"

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_cart_path(@cart)
\|
= link_to 'Back', carts_path