config/routes.rb
FoodpalApp::Application.routes.draw do

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  get "/errors/not_found"
  get "/errors/internal_error"
  get "/errors/unacceptable"
  get "/errors/unauthorized"

  get "omniauth_callbacks/facebook"

  get "restaurants/new"
  post "restaurants/create"

  match "products/create"

  put "products/update"

  delete "products/delete"

  post "products/edit"
  post "products/get_product"

  get "sendtext/index"
  post "sendtext/send_text_message"
  get "sms" => "receivetext#index"

  match "menus/create"

  put "menus/update"

  delete "menus/delete"
  post "menus/edit"

  match "contact", to: "static_pages#contact", as: "contact"
  match "dispatch_email", to: "static_pages#dispatch_email",
        as: "dispatch_email", method: :post


  post "comments/create"

  delete "gallery/delete"
  post "gallery/create"

  resources :gallery

  post "locations/create"

  post "restaurants/get_cuisine"

  get "restaurants/list"
  get "orders/list"

  post "products/create"

  mount Ckeditor::Engine => '/ckeditor'

  post "restaurants/craving_restaurants"
  post "restaurants/craving_blogs"



  post "cuisines/create"
  delete "cuisines/delete"

  get "orders/index"
  #get "order/:id" => "orders#show"
  resources :orders, only: [:show]
  resources :line_items

  get "locations/get_l_state"
  get "locations/get_l_city"
  get "locations/select_state"
  post "locations/edit"
  put "locations/update"
  delete "locations/delete"

  post "orders/status"
  get "orders/restaurants_orders/:id" => "orders#restaurants_orders"
  resources :carts

  get "restaurants/listing" => "restaurants#listing"

  resources :restaurants, only: [:show, :edit, :destroy, :update]
  #resources :users, only: [:edit]

  post "blogs/create"

  get "cities/index"
  resources :blogs, except: [:create]


  root :to =>  "restaurants#index"

  get "user" => "users#index"
  get "users/list"

  get "restaurants/index"
  post "restaurants/vote"


 post "restaurants/search"
post "restaurants/import_excel"
  post "restaurants/locations_import_excel"

  #get  "/restaurant/:id",   to:  "restaurants#show"

 post 'line_items/remove_item'


  get "about_us"                    => "static_pages#about_us"
  get "careers"                     => "static_pages#careers"
  get "founder_of_foodpal"          => "static_pages#founder"
  get "privacy_policy"              => "static_pages#private_policy"
  get "iphone_mobile_application"   => "static_pages#iphone"
  get "how_foodpal_works"           => "static_pages#how_works"
  get "media_kit"                   => "static_pages#media_kit"

  post "payments/payment"

  #get "blog"                        => "blogs#index"
  #get "/blogs/:id",  to:   'blogs#show'

  get "users/select_country"
  get "users/select_state"
  put "users/update"
  put "users/update"
  put "users/update_user"
  get "users/ready_city"
  get "users/get_user_state"
  get "users/get_user_city"
  put "users/update_password"
  get "users/user_edit"

  post "users/generate_new_password_email"
  #put "users/edit"

  get "receivetext/index"
  post "receivetext/voice"
  #get "receivetext/voice"

  resources :cuisines do
    get :autocomplete_cuisine_name, :on => :collection
  end

    #get "cuisines/autocomplete"

  match '/users/auth/:service/callback' => 'users/services#create'
  resources :services, :only => [:index, :create, :destroy]

  devise_for :users,  :controllers => { :sessions => "admins/sessions", :registrations=> "admins/registrations"},
                                      path_names: { edit_user_registration: "/",
                                      sign_out: "logout" }


  namespace :api do

    namespace :users do
      post "sign_in"

      post "create"
      
      post "sign_up"

      post "destroy"

      post 'orders'

      match "update"

      get "show"
    end

    namespace :orders do
      get "create_cart"
    end

    namespace :restaurants do

      post "search"

      #get "show"

      get "menu"

      get "set_select_params"

      match 'search_by_params'
      match 'search_restaurants'
      match 'get_from_current_location'


      get 'set_menu'
      get 'set_menu_items'
    end

    namespace :menus do
      match "get_menu_list"
    end

    namespace :products do
      match "get_product_list"
    end

    namespace :galleries do
      match "get_photo_list"
      match "get_first_photo"
    end

    namespace :comments do
      match "list"
    end

    namespace :payments do
      match "payment"
    end


    get 'logout' => 'devise/sessions#new'


  end

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admins do
  #     # Directs /admins/products/* to admins::ProductsController
  #     # (app/controllers/admins/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'


end

app/controllers/api/restaurants_controller.rb
class Api::RestaurantsController < ApplicationController
  before_filter :api_authentikate_user, except: [:set_select_params,
                                                 :search_by_params,
                                                 :set_menu,
                                                 :search_restaurants,
                                                 :get_menu_list,
                                                 :get_from_current_location ]

  def search
    puts '----------------restaurant-----------------------'
    puts params
    render json: params


    #$.ajax({
    #           type: 'POST',
    #           url: 'http://localhost:3000/api/restaurants/search',
    #
    #           success: function(data) { console.log(data) },
    #           error: function(data) { console.log(data['responseText']) },
    #
    #           data: {authentication_token: auth_token, params: {name: '122@v.v', cuisine: '11111111',  rating: '3'}},
    #
    #       });
  end

  def show
    puts '----------------restaurant-----------------------'

    render json: params

    #$.ajax({
    #           type: 'GET',
    #           url: 'http://localhost:3000/api/restaurants/show',
    #
    #           success: function(data) { console.log(data) },
    #           error: function(data) { console.log(data['responseText']) },
    #
    #           data: {authentication_token: auth_token, hotel_id: 12},
    #
    #       });
    #puts params

  end

  def menu
    puts '----------------restaurant-----------------------'
    puts params
    render json: params
  end

  def set_select_params
    puts "--------------set---select---params--------------------------------"
    sities = ActiveRecord::Base.connection.select_all("SELECT DISTINCT cities.city  FROM locations, cities, menus WHERE locations.city_id = cities.id AND menus.restaurant_id = locations.restaurant_id")
    sities = sities.map{ |hash| hash.values}.flatten! unless sities.blank?

    cusines = ActiveRecord::Base.connection.select_all(" SELECT DISTINCT cuisines.name FROM  cuisines
       LEFT JOIN restaurants ON (cuisines.restaurant_id= restaurants.id);")
    cusines= cusines.map{ |hash| hash.values}.flatten! unless sities.blank?
    list = {cities: sities, cuisines: cusines }
    puts list.to_s.green.bold
    render json: list.to_json
  end

  def search_by_params
    puts "--------------seach  restaurants--------------------------------"
    puts params.inspect

    city_par = params[:city]
    cuisine = params[:cusine]
    rating = params[:rating]
    keyword = params[:search_parametr]


    puts(city_par == 'City')
    puts(cuisine)
    puts(rating)
    puts(keyword)


    city = (params[:city] && params[:city] != "City" ) ? "AND cities.city = '#{params[:city]}' " : ""
    city2 = (city_par == "City" || !params[:city]) ? "OR cities.city LIKE '%#{keyword}%' OR cities.zip LIKE  '%#{keyword}%'" : ""


    cuisine_val = (cuisine == "Cuisine" || !cuisine) ? "" : "AND (cuisines.`name` LIKE '%#{cuisine}%')"
    cuisine_ref = (cuisine == "Cuisine"  || !cuisine) ? "" : "AND cuisines.restaurant_id = restaurants.id"

    rating_val = (rating == "Rating" || !rating) ? "" : "AND (restaurants.`rating` LIKE '%#{rating}%')"

    puts cuisine_ref.inspect.green.bold
    puts rating_val.inspect.green.bold
    puts city.inspect.yellow.bold
    puts city2.inspect.yellow.bold


    c1 = (cuisine == "Cuisine" || !cuisine) ? "" : "join cuisines cu on cu.restaurant_id = r.id"
    c2 = (cuisine == "Cuisine" || !cuisine) ? "" :"AND cu.`name` LIKE '%#{cuisine}%'"

    r2 = (rating == "Rating" || !rating) ? "" :" AND r.`rating` = #{rating}"

    s_r = "join restaurants r on l.restaurant_id = r.id join cities c on l.city_id = c.id join states s on c.state_id = s.id"
    s_v = "r.name LIKE '%#{keyword}%' OR c.city LIKE '%#{keyword}%' OR l.zip LIKE '%#{keyword}%' OR s.state LIKE '%#{keyword}%' OR s.state_code LIKE '%#{keyword}%'"


    @locations = Location.find_by_sql("SELECT  l.*
    FROM locations l #{s_r}
    #{c1}
    WHERE (#{s_v}
          ) AND
    r.delivery_type in (0, 1) #{c2} #{r2}
    AND ((l.latitude > 0) OR (l.latitude < 0))
    AND ((l.longitude > 0) OR (l.longitude < 0));")

    # @locations = Location.find_by_sql("SELECT DISTINCT
    #                   locations.*
    #                 FROM
    #                   locations,
    #                   restaurants,
    #                  cities,
    #                   states,
    #                   cuisines
    #                 WHERE
    #                   locations.restaurant_id = restaurants.id
    #                   AND locations.city_id = cities.id
    #                   AND cities.state_id = states.id
    #                   #{cuisine_ref}
    #                 AND (
    #                   restaurants.name LIKE '%#{keyword}%'
    #                   OR states.state LIKE '%#{keyword}%'
    #                   OR states.state_code LIKE '%#{keyword}%'
    #                   #{city2}
    #                 ) #{cuisine_val}
    #                                   #{rating_val}
    #                                   #{city}"
    #
    # )








    #@locations = Location.find_by_sql("SELECT DISTINCT
    #                  locations.*
    #                FROM
    #                  locations,
    #                  restaurants,
    #                 cities,
    #                  states,
    #                  cuisines
    #                WHERE
    #                  locations.restaurant_id = restaurants.id
    #                  AND locations.city_id = cities.id
    #                  AND cities.state_id = states.id
    #
    #                AND (
    #                  restaurants.name LIKE '%#{search_parametr}%'
    #                  OR cities.city LIKE '%#{search_parametr}%'
    #                  OR cities.zip LIKE  '%#{search_parametr}%'
    #                  OR states.state LIKE '%#{search_parametr}%'
    #                  OR states.state_code LIKE '%#{search_parametr}%'
    #                ) "
    #)




      if @locations.nil?

        render json: {locations: []}.to_json
      end

  end

  def search_restaurants
    puts "--------------seach  restaurants--------------------------------"
    puts params.inspect

    keyword = params[:keyword]
    city = (params[:city] != "" && params[:city]) ? "AND cities.city = '#{params[:city]}' " : ""
    city2 = (params[:city] == "" || !params[:city]) ? "OR cities.city LIKE '%#{keyword}%' OR cities.zip LIKE  '%#{keyword}%'" : ""
    cuisine = params[:cuisine]
    rating = params[:rating]

    cuisine_val = (cuisine == "" || !cuisine) ? "" : "AND (cuisines.`name` LIKE '%#{cuisine}%')"
    cuisine_ref = (cuisine == ""  || !cuisine) ? "" : "AND cuisines.restaurant_id = restaurants.id"

    rating_val = (rating == "" || !rating) ? "" : "AND (restaurants.`rating` LIKE '%#{rating}%')"

    puts rating.inspect.green.bold
    puts params.inspect.yellow.bold

    @locations = Location.find_by_sql("SELECT DISTINCT
                      locations.*
                    FROM
                      locations,
                      restaurants,
                     cities,
                      states,
                      cuisines,
                      menus
                    WHERE
                      locations.restaurant_id = restaurants.id
                      AND locations.city_id = cities.id
                      AND cities.state_id = states.id
                      AND menus.restaurant_id = locations.restaurant_id
                      #{cuisine_ref}
                    AND (
                      restaurants.name LIKE '%#{keyword}%'
                      OR states.state LIKE '%#{keyword}%'
                      OR states.state_code LIKE '%#{keyword}%'
                      #{city2}
                    ) #{cuisine_val}
                                      #{rating_val}
                                      #{city}"

    )

    #cu1 = cuisine == "" ? "" :"join cuisines cu on cu.restaurant_id = r.id"
    #cu2 = cuisine == "" ? "" :"AND cu.`name` LIKE '%#{cuisine}%'"
    #
    #c1 = (params[:city] == "" && !params[:city]) ? "" :"join cities c on l.city_id = c.id"
    #c2 = (params[:city] == "" && !params[:city]) ? "" :"AND cu.`name` LIKE '%#{cuisine}%'"

#    @locations = Location.find_by_sql("SELECT  l.*
#FROM locations l join
#     restaurants r
#     on l.restaurant_id = r.id join
#     states s
#     on c.state_id = s.id
##{cu1}
##{c1}
#WHERE (r.name LIKE '%#{zip}%' OR
#       c.city LIKE '%#{zip}%' OR
#       l.zip LIKE '%#{zip}%' OR
#       s.state LIKE '%#{zip}%' OR
#       s.state_code LIKE '%#{zip}%'
#      ) AND
#      r.delivery_type in (0, 1) #{cu2}
#AND ((l.latitude > 0) OR (l.latitude < 0))
#AND ((l.longitude > 0) OR (l.longitude < 0));")


    puts( @locations.inspect.red)


    if @locations.nil?

      render json: {locations: []}.to_json
    end

  end

  def get_from_current_location
    puts params.inspect.green

    latitude = params[:latitude]
    longitude = params[:longitude]

    @locations = Location.find_by_sql("SELECT DISTINCT
                      locations.*, geo_distance (
                                    #{latitude},
                                    #{longitude},
                                    ifnull(latitude + 0, 0.0),
                                    ifnull(longitude + 0, 0.0)
                                  ) AS `distance`
                    FROM
                      locations,
                      restaurants,
                     cities

                    WHERE
                      locations.restaurant_id = restaurants.id
                      AND locations.city_id = cities.id

                    HAVING
	                    distance <= 500")


    puts( @locations.inspect.red)

    if @locations.nil?

      render json: {locations: []}.to_json

    end
  end

  def set_menu
    puts '----------set-----------------manu---------------------'

app/helpers/api/restaurants_helper.rb
module Api::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper


end

app/views/restaurants/_grid.html.haml
-#- show_filters: :when_filtered
=  grid(@restaurants, show_filters: :when_filtered, allow_showing_all_records:  false) do |g|
  - g.column name:  '#', attribute: 'id'
  - g.column name:  'Name', attribute: 'name' do |task|
    - link_to(task.name, edit_restaurant_path(task))

  - g.column name:  '' do |task|
    - raw "<div>
    - <span class=\"label label-primary\">Locations: #{task.locations.count}</span>
    - <span class=\"label label-success\">Menu: #{task.menus.count}</span>
    - <span class=\"label label-warning\">Products: #{
    - task.menus.map{|menu| menu.products}.flatten!.count unless task.menus.map{|menu| menu.products}.flatten!.blank?
    - }#{
    - 0 unless !task.menus.map{|menu| menu.products}.flatten!.blank?
    - }</span>
    - <span class=\"label label-default\">Photos: #{task.galleries.count}</span>
    - </div>"

  - g.blank_slate content_tag(:div, "No restourants found", class: 'well')

app/views/restaurants/_rest_page.html.haml
%h1
  Rest_page
= @selected_rest

app/views/restaurants/edit.html.haml
.content
  .loading.restaurant
    %img(src="/assets/loading.gif" ){style: "margin: 0 auto"}

  - if @restaurant

    .post.restaurant

      = form_for @restaurant, url: restaurant_path(@restaurant), method: "PUT" do |form|
        .row{style: "margin: 0"}
          .col-xs-10
            %h1
              = link_to image_tag("/assets/DeleteRed.png", :style => "width: 24px"), restaurant_path(@restaurant), method: "delete", data: {:confirm => "Are you shure? o_O"}
              Edit
              = "\"" + @restaurant.name + "\""
          .col-xs-2
            = form.submit "Save Changes", class: "btn btn-success"




        .row
          .col-xs-5
            .field{style: "text-align: center"}
              = image_tag @restaurant.image.url(:thumb), style: "margin: 10px"
              = form.file_field :image
          .col-xs-7
            .field
              = form.label :name
              = form.text_field :name, class: "white textfield required"

        .field
          = form.label :description
          = form.text_area :description, class: "white"

        .row
          .col-xs-6

            .field
              = form.label :email
              = form.text_field :email, class: "white email"
          .col-xs-6
            .field
              = form.label :url
              = form.text_field :url, class: "white url"

        .row
          .col-xs-6
            .field
              = label_tag "Delivery Method"
              = form.radio_button(:delivery_type, 0, class: "css-checkbox")
              %label.css-label{for: "restaurant_delivery_type_0"} Both

              = form.radio_button(:delivery_type, 1, class: "css-checkbox")
              %label.css-label{for: "restaurant_delivery_type_1"} Pick Up

              = form.radio_button(:delivery_type, 2, class: "css-checkbox")
              %label.css-label{for: "restaurant_delivery_type_2"} Delivery

          .col-xs-6
            .field
              = label_tag "Payment Method"
              = form.radio_button(:payment_type, 0, class: "css-checkbox")
              %label.css-label{for: "restaurant_payment_type_0"} Both

              = form.radio_button(:payment_type, 1, class: "css-checkbox")
              %label.css-label{for: "restaurant_payment_type_1"} Cash

              = form.radio_button(:payment_type, 2, class: "css-checkbox")
              %label.css-label{for: "restaurant_payment_type_2"} Card

        %fieldset.row.fieldset
          %legend
            Socials

          .row
            .col-xs-4
              = form.label :facebook_url
              = form.text_field :facebook_url, class: "white url"

            .col-xs-4
              = form.label :twitter_url
              = form.text_field :twitter_url, class: "white url"

            .col-xs-4
              = form.label :g_url
              = form.text_field :g_url, class: "white url"


        %fieldset.row.fieldset
          %legend
            Other
          .other
            = label_tag "Show restaurant at Free Restaurant Listing Application"
            = form.radio_button(:list, false, class: "css-checkbox")
            %label.css-label{for: "restaurant_list_false"} No

            = form.radio_button(:list, true, class: "css-checkbox")
            %label.css-label{for: "restaurant_list_true"} Yes

      %fieldset.row.fieldset
        %legend
          Cuisines
        .cuisines
          = render partial: "cuisines/list_by_restaurant", locals: {restaurant: @restaurant}

      %fieldset.row.fieldset
        %legend
          Locations
        .locations
          = render partial: "locations/list_by_restaurant", locals: {restaurant: @restaurant}

      %fieldset.row.fieldset
        %legend
          Menus

        = image_tag("/assets/ImportExcel.bmp", id: "import", style: "float: right");

        %br
        .menus
          = render partial: "menus/list", locals: {restaurant: @restaurant}

      %fieldset.row.fieldset
        %legend
          Photos

        .gallery
          = render partial: "gallery/list_by_restaurant", locals: {restaurant: @restaurant}



  :javascript
    $(document).ready(function(){
      $('.edit_restaurant').validate();
    })

#importMenu.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Load Menus from Exel
      .modal-body{style: "overflow: hidden"}
        =form_tag(restaurants_import_excel_path({rest_id: @restaurant.id}), :multipart=>true, :method => 'post') do
          Select an Excel File :
          = file_field_tag 'excel'
          = submit_tag 'load', class: 'btn btn-primary btn-success', :id => 'load_excel', :style => "float: right"

#addImage.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      - @gallery = Gallery.new
      = form_for @gallery, url: "/gallery/create", :html => { :id => "imageUploadForm", :multipart => true } do |form|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4#myModalLabel.modal-title Add Image
        .modal-body{style: "max-height: 414px;overflow: auto;"}
          .writing.gallery
            %img(src="/assets/writing.gif" ){style: "margin: 0 auto"}
          .form
            = form.file_field :image, class: "required"
            = form.hidden_field :restaurant_id, :value => @restaurant.id.to_s

        .modal-footer
          = form.submit "Add image", class: "btn btn-success"

        :javascript
          $(document).ready(function(){
            $('#imageUploadForm').validate();
          })

app/views/restaurants/index.html.haml
#searchbox
  .row
    .col-xs-5
      .searchinner{style: "height: 360px"}
        - @cuisines = Cuisine.new
        = form_for @cuisines, url: root_path, id: 'form_for_search' do |f|
          %div.field
            Search by: 
            #togle-buttons.btn-group.btn-group-sm{role: "toolbar", style: "margin: 10px 0"}
              %button.btn.btn-default.active{type: "button", "data-filter" => 0} All
              %button.btn.btn-default{type: "button", "data-filter" => 1} Restaurant
              %button.btn.btn-default{type: "button", "data-filter" => 2} City
              %button.btn.btn-default{type: "button", "data-filter" => 3} Zip
              %button.btn.btn-default{type: "button", "data-filter" => 4} State
            = text_field_tag :name, '', :autofocus => true, style: "width: 254px", class: "white required"
            and/or
          %div.field
            = label_tag "Type of Cuisine"
            %br
            -#= text_field_tag :cuisine, nil, class: "cuisine"
            = autocomplete_field_tag 'cuisine', '', autocomplete_cuisine_name_cuisines_path, class: "white"
            -#= f.autocomplete_field :name, cuisines_autocomplete_path
          %div.field
            = label_tag "Method"

            %br
            = radio_button_tag(:delivery, 1, true, class: "css-checkbox")
            %label.css-label{for: "delivery_1"} Delivery
            -#= label(:delivery_child, "Delivery")
            %br
            = radio_button_tag(:delivery, 0, false, class: "css-checkbox")
            %label.css-label{for: "delivery_0"} Pick up
            -#= label_tag(:delivery_adult, "Pick up")


          %div.field.text-center
            = submit_tag "GO!", :id => 'search_form', class: "dark", style: "width: 100px; margin: 0 auto; padding: 5px; font-size: 22px"

    .col-xs-7

      #map-loader
        .image{style: "position: absolute; z-index: 1000; top: 7%; left: 26.5%"}
          %img(src="assets/loading_spin.gif" )
        .flash
          .close_button
          %p Not any restaurants found

        %div#map
  .row
    .col-xs-12
      #indicator

.block
  .row
    .col-xs-7
      %h1.green
        FOLLOW US ANYWHERE
        %ul
          %li
            %a{href: "https://www.facebook.com/FoodPal", target: "_blank"}
              %img(src="assets/fb.png" )
          %li
            %a{href: "https://twitter.com/FoodpalLLC", target: "_blank"}
              %img(src="assets/twitter.png" )
          %li
            %a{href: "https://plus.google.com/u/0/+Foodpal/posts", target: "_blank"}
              %img(src="assets/googlep.png" )

      .quote.green-bottom
        %p “Foodpal allows me to connect with all of my favorite restaurants within minutes!”
        \- Robin Hunting
    .col-xs-5.text-center
      .mobile.green-bottom
        %h2.green FOODPAL MOBILE
        %ul
          %li
            %a(href=iphone_mobile_application_path)
              %img(src="assets/IPhone.png" )

          %li
            %a(href="#")
              %img(src="assets/IPad.png" )

          %li
            %a(href="#")
              %img(src="assets/Android.png" )

.block
  .row#restaurant_page
    = render partial: 'index_content'

.block
  .row
    .col-xs-12
      %h2.green See What the Rave is About:
      #carousel-generic
        .carousel-inner
          .item.active
            %ul
              %li
                %img(src="/assets/partners/partner_0.png" )
              %li
                %img(src="/assets/partners/partner_1.png" )
              %li
                %img(src="/assets/partners/partner_2.png" )
              %li
                %img(src="/assets/partners/partner_3.png" )
              %li
                %img(src="/assets/partners/partner_4.png" )
          .item
            %ul
              %li
                %img(src="/assets/partners/partner_4.png" )
              %li
                %img(src="/assets/partners/partner_3.png" )
              %li
                %img(src="/assets/partners/partner_0.png" )
              %li
                %img(src="/assets/partners/partner_3.png" )
              %li
                %img(src="assets/partners/partner_1.png" )

        %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-generic"}
          %span.glyphicon.glyphicon-chevron-left
        %a.right.carousel-control{"data-slide" => "next", href: "#carousel-generic"}
          %span.glyphicon.glyphicon-chevron-right

:javascript
  $(document).ready(function () {
      $("#map-loader .image").css("display", "block");
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showLocation, showError);
      } else {
          alert("Geolocation is not supported by this browser.")
      }

      var params = getHashParams();

      if (typeof params.key == "undefined" && typeof params.cuisine == "undefined" && typeof params.delivery == "undefined" && typeof params.filter == "undefined") {

        console.log("Empty");
      } else {

        console.log(params.key + " " + params.cuisine + " " + params.delivery + " " + params.filter );

          $("#name").val(params.key);
          $("#cuisine").val(params.cuisine);

          if (params.delivery == 1) {
              $("#delivery_1").prop('checked', true);
          } else {
              $("#delivery_0").prop('checked', true);
          }


          if (params.filter == "" || params.filter == null) {
              params.filter = 0;
          }
          $("#togle-buttons  button").removeClass("active");
          $("#togle-buttons button[data-filter='" + params.filter + "']").addClass("active");


          if (localStorage.getItem("rest-data") != null && localStorage.getItem("rest-data") != "") {
              if (localStorage.getItem("keyword") == params.key
                  && localStorage.getItem("cuisine") == params.cuisine
                  && localStorage.getItem("delivery") == params.delivery
                  && localStorage.getItem("filter") == params.filter)  {

                  $('#restaurant_list').html(localStorage.getItem("rest-data"));
              } else {
                  loadData();
              }
          } else {
              //loadData();
          }

      }

  });